### ISSUE TITLE
Provide Duration as `std::time::Duration`

### ISSUE THREAD

**Issue by shtrophic** [theduke/ffprobe-rs#11]
Wouldn't it be more intuitive if the `duration` field provided by ffprobe is returned as `std::time::Duration`?

Obviously, this can easily be parsed into, but I suggest adding this directly to the api.

**Comment by theduke** [comment]
Absolutely.

The ffrpobe output has durations as a string (like `"13.960000"`), which is a bit awkward to parse with `serde` and requires a custom deserializer impl. Nothing dramatic , but I was in a hurry and punted. 

I also wasn't sure if the duration is always in the same format.

The easy path would be adding an accessor method that does the parsing.

**Comment by theduke** [comment]
Fixed/released in `0.3.3`.
