### ISSUE TITLE
Add `reel_name` as a StreamTag

### ISSUE THREAD

**Issue by brimestoned** [theduke/ffprobe-rs#17]
Requesting `reel_name` to be added to StreamTag

![image](https://user-images.githubusercontent.com/41085428/205718498-f5d299bf-5188-49fe-a7ea-f4aac2bcb4c6.png)

Also, I would love to contribute to this crate as I use ffprobe all the time.

**Comment by theduke** [comment]
Makes sense.

Happy to get a PR!

**Comment by theduke** [comment]
Closed by #18
