### ISSUE TITLE
ffprobe fails silently when running inside a separate spawned thread

### ISSUE THREAD

**Issue by couleurm** [theduke/ffprobe-rs#24]
Hey, is there a reason why this does not work in Rust threading that I haven't grasped, or is there something up with ffprobe?

```rs
fn main() {
    std::thread::spawn(
        move || match ffprobe::ffprobe("D:\\video.mp4") {
            Ok(info) => {
                dbg!(info);
            }
            Err(err) => {
                eprintln!("Could not analyze file with ffprobe: {:?}", err);
            }
        },
    );
}
```

**Comment by theduke** [comment]
You are not waiting for the thread to finish, so `main()` will exit immediately before the thread has a chance to run.

You need to do `spawn().join()`.
