### ISSUE TITLE
Documentation: Examples

### ISSUE THREAD

**Issue by JoelMon** [theduke/ffprobe-rs#3]
Hello, 

Would it be possible to get a few examples into the documentation. 

If I figure it out before the docs are updated then I'll add them if you'll like.

Thanks!

**Comment by theduke** [comment]
Sure, we can add an example, but the API is very limited.

There is just a single function: https://docs.rs/ffprobe/0.1.0/ffprobe/fn.ffprobe.html

Use it like this: 

```rust
let data = ffprobe::ffprobe("/path/to/file.mp4").unwrap();
dbg!(data);
```

**Comment by JoelMon** [comment]
I'm going to try that line of code again, last time I tried, it didn't work...
