### ISSUE TITLE
Provide errors as enum

### ISSUE THREAD

**Issue by MCOfficer** [theduke/ffprobe-rs#6]
It would be helpful if `FfProbeError` was an enum, so one could easily check for the category of error programmatically. My usecase: I would like to log deserialization errors prominently so i can report them here, but the only way to do that is a `str::contains` on the error message.

The way i see it, there are currently 3 types of errors that are being wrapped:

https://github.com/theduke/ffprobe-rs/blob/88eedce369dd7a2ad29799d40d46ae55fd6f74ba/src/lib.rs#L25-L48

I would propose the following variants:

- `Io(std::io::Error)` for errors originating from the ffprobe invocation, for example if the command was not found
- `Status(std::process::Output)` for invalid exit codes
- `Deserialize(serde_json::Error)` for failure to deserialize

I'm willing to provide a PR, just asking for an opinion beforehand.

**Comment by MCOfficer** [comment]
This would be greatly beneficial to my fuzzing of the project. I've gathered 19 thousand test files at https://video-samples.mcofficer.me/, but my test setup is a bit inconvenient with the current errors. I guess I'll resort to invoking ffprobe myself to find the original json for now.

Here's a bit of a sneak peek using v0.2.0 (#5 should reduce these numbers quite a bit):

```
Starting, expect a lot of IO usage
Running ffprobe for 19305 files
Analying results
Success: 7271
FFProbe crashed (includes non-video files): 6501
Serde errors: 5533
IO Errors during invocation: 0
```

**Comment by theduke** [comment]
Sure, that's perfectly fine with me.

PR is appreciated.
